add support for fullscreen toggle + keyboard shortcut
smol-ai/menubar pull request #68
Opened 2023-07-15 21:23 UTC by seanoliver

I noticed that I'm spending a lot of time dragging to resize the menubar to make it fullscreen. With this small update, you can hit `Cmd` + `Shift` + `F` (which is conveniently right next to `Cmd` + `Shift` + `G`!) to toggle back and forth between full viewport width and the default 1200 pixel width.

Great for people on ultra-wide monitors, you can probably now easily fit 6 or 7 providers side-by-side.

This demo video shows it on my laptop screen but I can take another one on my super-wide monitor when I get a chance if we think it's worth sharing!

https://github.com/smol-ai/menubar/assets/882952/21056599-4657-4a25-b622-252a3b7654a7

2023-07-16 00:13 UTC, swyxio requested changes
looking good, but please update readme when you add new functionality! make it a habit. no doing without telling.

2023-07-16 02:05 UTC, seanoliver commented
Ah thanks! Updated the README and will make it a habit.

2023-07-16 18:21 UTC, swyxio approved these changes

2023-07-16 18:21 UTC, merged

2023-07-31 09:59 UTC, Eggwise commented
@seanoliver How can i disable this?

Now i cant use CMD SHIFT F5 in my other applications while Smol is on...
I use it to find in files in my IDEA. So this is very annoying

2023-07-31 13:13 UTC, lgandecki commented
I think this is probably an overkill, there is a ton of apps that help resize windows on MacOS. If someone doesn't use them, but feels the need to full screen this one.. most probably that person would find it helpful to full screen other apps as well, using a universal tool. 
I currently use https://www.raycast.com/ for that, but it does a lot of other things as well. I used to use totalspaces (but with raycast it didn't make sense to have two apps do the same thing). Sizeup is small and great for it as well.

Adding a lot of keyboard shortcuts here especially since they are difficult to modify is probably not the way to go. I don't think I've ever seen an app implement a full-screen toggle like that manually, not sure if this is THE ONE that needs it :)

just my opinion of course, feel free to ignore it - but the fact of clashing shortcuts is definitely problematic, especially since we can achieve the same thing in more standard way.

2023-08-02 05:13 UTC, seanoliver commented
Oh fine. Repealed in #104 
![giphy](https://github.com/smol-ai/menubar/assets/882952/c2f1d9f2-b9ae-4505-9707-74e590084898)